-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  action text NOT NULL,
  entity_type text,
  entity_id uuid,
  changes jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_activity_log_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  talent_id uuid NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in-progress'::text, 'interview-scheduled'::text, 'offered'::text, 'hired'::text, 'rejected'::text, 'maybe'::text, 'archived'::text])),
  stage text CHECK (stage IS NULL OR (stage = ANY (ARRAY['to-contact'::text, 'talent-acquisition'::text, 'technical'::text, 'leadership'::text, 'offer'::text, 'rejected-offer'::text, 'hired'::text]))),
  match_score integer,
  cover_letter text,
  resume_url text,
  applied_at timestamp with time zone DEFAULT now(),
  reviewed_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT applications_pkey PRIMARY KEY (id),
  CONSTRAINT fk_application_job FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT fk_application_talent FOREIGN KEY (talent_id) REFERENCES public.talents(id)
);
CREATE TABLE public.employer_team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text DEFAULT 'recruiter'::text CHECK (role = ANY (ARRAY['admin'::text, 'recruiter'::text, 'hiring-manager'::text, 'viewer'::text])),
  is_active boolean DEFAULT true,
  invited_by uuid,
  joined_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  first_name text,
  last_name text,
  phone text,
  CONSTRAINT employer_team_members_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_member_employer FOREIGN KEY (employer_id) REFERENCES public.employers(id),
  CONSTRAINT fk_team_member_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_team_member_invited_by FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.employers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  company_name text NOT NULL,
  tagline text,
  description text,
  industry text,
  website text,
  company_size text,
  year_founded text,
  address text,
  city text,
  country text,
  zip_code text,
  linkedin_url text,
  facebook_url text,
  logo_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  rep_first_name text,
  rep_last_name text,
  CONSTRAINT employers_pkey PRIMARY KEY (id),
  CONSTRAINT employers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.interview_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  interview_id uuid NOT NULL UNIQUE,
  rating numeric NOT NULL CHECK (rating >= 1::numeric AND rating <= 5::numeric),
  review_text text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT interview_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT fk_interview_review_interview FOREIGN KEY (interview_id) REFERENCES public.interviews(id)
);
CREATE TABLE public.interviewers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  employer_id uuid,
  full_name text NOT NULL,
  email text NOT NULL UNIQUE,
  expertise ARRAY,
  interview_type text NOT NULL CHECK (interview_type = ANY (ARRAY['technical'::text, 'leadership'::text, 'talent-acquisition'::text])),
  role text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT interviewers_pkey PRIMARY KEY (id),
  CONSTRAINT interviewers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT interviewers_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES public.employers(id)
);
CREATE TABLE public.interviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  interviewer_id uuid,
  interview_type text NOT NULL CHECK (interview_type = ANY (ARRAY['technical'::text, 'leadership'::text, 'talent-acquisition'::text])),
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'confirmed'::text, 'completed'::text, 'cancelled'::text, 'rescheduled'::text, 'no-show'::text])),
  scheduled_date timestamp with time zone NOT NULL,
  duration_minutes integer DEFAULT 60,
  meet_link text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_member_id uuid,
  created_by uuid,
  CONSTRAINT interviews_pkey PRIMARY KEY (id),
  CONSTRAINT fk_interview_application FOREIGN KEY (application_id) REFERENCES public.applications(id),
  CONSTRAINT fk_interviews_interviewer FOREIGN KEY (interviewer_id) REFERENCES public.interviewers(id),
  CONSTRAINT interviews_team_member_id_fkey FOREIGN KEY (team_member_id) REFERENCES public.employer_team_members(id),
  CONSTRAINT fk_interviews_created_by FOREIGN KEY (created_by) REFERENCES public.employer_team_members(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_id uuid NOT NULL,
  title text NOT NULL,
  profession text,
  description text,
  location text,
  workplace text CHECK (workplace = ANY (ARRAY['on-site'::text, 'remote'::text, 'hybrid'::text])),
  employment_type text CHECK (employment_type = ANY (ARRAY['full-time'::text, 'part-time'::text, 'contract'::text, 'internship'::text])),
  contract_type text,
  experience_level text,
  job_level text,
  education_required text,
  skills_required ARRAY,
  positions_available integer DEFAULT 1,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['published'::text, 'unpublished'::text, 'archived'::text])),
  applicants_count integer DEFAULT 0,
  views_count integer DEFAULT 0,
  published_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_job_employer FOREIGN KEY (employer_id) REFERENCES public.employers(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text CHECK (notification_type = ANY (ARRAY['application'::text, 'interview'::text, 'job'::text, 'message'::text, 'system'::text])),
  related_id uuid,
  is_read boolean DEFAULT false,
  action_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  application_id uuid NOT NULL,
  position character varying NOT NULL,
  salary character varying NOT NULL,
  start_date date NOT NULL,
  work_location character varying,
  benefits_perks text,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'refused'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offers_pkey PRIMARY KEY (id),
  CONSTRAINT offers_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.applications(id)
);
CREATE TABLE public.owners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  full_name text NOT NULL,
  phone_number text,
  city text,
  country text,
  bio text,
  profile_photo_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT owners_pkey PRIMARY KEY (id),
  CONSTRAINT owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employer_id uuid NOT NULL,
  card_type text NOT NULL,
  card_last4 text NOT NULL,
  card_brand text,
  expiry_month integer NOT NULL,
  expiry_year integer NOT NULL,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payment_method_employer FOREIGN KEY (employer_id) REFERENCES public.employers(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL,
  employer_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  payment_method text,
  transaction_id text UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text, 'cancelled'::text])),
  invoice_url text,
  receipt_url text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_payment_employer FOREIGN KEY (employer_id) REFERENCES public.employers(id)
);
CREATE TABLE public.plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  display_name text NOT NULL,
  description text,
  target_user_type text NOT NULL CHECK (target_user_type = ANY (ARRAY['employer'::text, 'talent'::text])),
  price numeric NOT NULL,
  billing_cycle text CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'annually'::text, 'one-time'::text])),
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  max_job_posts integer,
  max_active_jobs integer,
  max_users integer,
  max_service_posts integer,
  max_active_services integer,
  features jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.service_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  rating numeric NOT NULL,
  review_text text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT service_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT fk_service_review_service FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT fk_service_review_reviewer FOREIGN KEY (reviewer_id) REFERENCES public.users(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  talent_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  category text,
  starting_price numeric,
  delivery_time text,
  rating numeric,
  reviews_count integer DEFAULT 0,
  tags ARRAY,
  icon text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT fk_service_talent FOREIGN KEY (talent_id) REFERENCES public.talents(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL,
  employer_id uuid,
  talent_id uuid,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'expired'::text, 'suspended'::text, 'trial'::text])),
  started_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  auto_renew boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_subscription_plan FOREIGN KEY (plan_id) REFERENCES public.plans(id),
  CONSTRAINT fk_subscription_employer FOREIGN KEY (employer_id) REFERENCES public.employers(id),
  CONSTRAINT fk_subscription_talent FOREIGN KEY (talent_id) REFERENCES public.talents(id)
);
CREATE TABLE public.talents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  full_name text NOT NULL,
  phone_number text,
  city text,
  current_position text,
  years_of_experience text,
  education_level text,
  job_types ARRAY,
  work_location ARRAY,
  short_bio text,
  linkedin_url text,
  github_url text,
  portfolio_url text,
  has_carte_entrepreneur boolean DEFAULT false,
  skills ARRAY,
  profile_photo_url text,
  resume_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT talents_pkey PRIMARY KEY (id),
  CONSTRAINT talents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  sender_name text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  ticket_type text DEFAULT 'Technical'::text CHECK (ticket_type = ANY (ARRAY['Technical'::text, 'Bug Report'::text, 'Feature Request'::text, 'Billing'::text, 'General'::text])),
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'viewed'::text, 'in-progress'::text, 'solved'::text, 'closed'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  assigned_to uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT tickets_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ticket_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  user_role text NOT NULL DEFAULT 'talent'::text CHECK (user_role = ANY (ARRAY['superadmin'::text, 'admin'::text, 'owner'::text, 'talent'::text, 'employer'::text, 'interviewer'::text])),
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  profile_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);